notifications:
  email: false
jobs:
  include:
  - stage: deploy backend to production
    language: python
    python:
    - '3.6'
    services:
    - postgresql
    addons:
      postgresql: '9.6'
    before_install:
    - cd backend
    install:
    - pip install -r requirements.txt
    before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    script: python manage.py test api
    deploy:
      provider: heroku
      app: yefdebug
      api_key:
        secure: dDr0ViFeOTue2JqZ/M5cGDzLxK4KplnOGDodmsX8x03jDIpHqnL47+dZRNuLkelYnHI5nOiRYvNq3p57bu2CsJcxi2sR7u7w5+ZNbyQTg/gusitPL/FlGRpixboayeRJF21qoxn6JR8UPHI44jEhC3HmJKayQHwI4l8d1jSQRkQrZaquvHS2v4FxxvDdGN0/63I/xNx9iF3h7gBg7GkBwn3/sy2lfWXJj3Gu7Jy5y2x47Iqsz1dUtfeB1Yt8ndHfNcmpC025Cbu9yH+wNx0xSyLQw7Cnt9Runo9lSkrooMozcU+/UPOrHt05/tQ0trWBN3OKm448aSlSv1YGzP58eIekURRfccLMsIvcqK4hLrYLn/SOS5tFZuKdUZMZID8b7ZtI0lECW6XlnzM0yjJUw5sDAZdXebopw5Mulc22ODUuCnhIyhh12s1pq6mMT5t8FtX4h2qx8WxKQfkELGa6tWYPyUholUZ0bEkJlhs++11sd3lOYqd2mhtDN5buLVQnrCJcWZ52FFRlsDlU+PRwBROqjThowB1CLDPRvm+K9UeS1F4PkWL1UDCEuFcXbDpOztxHE9kaUbQQtJWvWL2W10SBwuI4t1YFK3i/cg8y4Sa7KCbQ2ueioLg7CxkNKzAoAz6wTbHXYFfrrpoWWnmr/tb5Sh7TcjWTe8jHARfoF4I=
  - stage: deploy frontend to production
    language: node_js
    node_js:
    - stable
    cache:
      directories:
      - client/node_modules
    script:
    - cd frontend
    deploy:
      provider: heroku
      app: yefdebugfrontend
    api_key:
        secure: dDr0ViFeOTue2JqZ/M5cGDzLxK4KplnOGDodmsX8x03jDIpHqnL47+dZRNuLkelYnHI5nOiRYvNq3p57bu2CsJcxi2sR7u7w5+ZNbyQTg/gusitPL/FlGRpixboayeRJF21qoxn6JR8UPHI44jEhC3HmJKayQHwI4l8d1jSQRkQrZaquvHS2v4FxxvDdGN0/63I/xNx9iF3h7gBg7GkBwn3/sy2lfWXJj3Gu7Jy5y2x47Iqsz1dUtfeB1Yt8ndHfNcmpC025Cbu9yH+wNx0xSyLQw7Cnt9Runo9lSkrooMozcU+/UPOrHt05/tQ0trWBN3OKm448aSlSv1YGzP58eIekURRfccLMsIvcqK4hLrYLn/SOS5tFZuKdUZMZID8b7ZtI0lECW6XlnzM0yjJUw5sDAZdXebopw5Mulc22ODUuCnhIyhh12s1pq6mMT5t8FtX4h2qx8WxKQfkELGa6tWYPyUholUZ0bEkJlhs++11sd3lOYqd2mhtDN5buLVQnrCJcWZ52FFRlsDlU+PRwBROqjThowB1CLDPRvm+K9UeS1F4PkWL1UDCEuFcXbDpOztxHE9kaUbQQtJWvWL2W10SBwuI4t1YFK3i/cg8y4Sa7KCbQ2ueioLg7CxkNKzAoAz6wTbHXYFfrrpoWWnmr/tb5Sh7TcjWTe8jHARfoF4I=
