notifications:
  email: false
jobs:
  include:
  - stage: deploy backend to production
    language: python
    services:
    - postgresql
    addons:
      postgresql: '9.6'
    before_install:
    - cd backend
    install:
    - pip install -r requirements.txt
    before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    deploy:
      provider: heroku
      app: yefdebug
      api_key:
        secure: ej3Egu8KqyHrWKIOVqSooioEhdKP3aAgbeUnk7gMbaQP7uZrwHPsiqFAe3pVRD3srqvLqUv3rLnUaMN7C6kAkQwD333xs6nzuhF1Ur8QXy8KwAI5Fu1Nj8x7cxjZdint9GMUT70j737JP2U86AhR9Bz67g0N9PC4/zHh2Td4vyBRCHZGYarfg6TIRaIZEuGOxw07SMzaDBEp8UZR6xdD4usutZgQgUzEbFku2ygoomxce0DhHrvcyEyovvhgPszYEFtPV6Puk95uNdwoudNi8lBqup0Vwq1bdwMe5cOf2Zk45RPsXq9mWo2DQUoHkd2JsER6OPhdU5HLoLqO0LUi/vHkPwr9nOMZWyWKTI7HJJ9y4vTBajkN0LPwIsIVmFzyVRb7gFPXkgs4hZ5/ERyiVEl3aKnKYDGL9oqhV31giEBLW2jYsQHxOSKOCQtmZT59ScjtUGiJdJxLumFRrIQ6wVxmsI3Wx+ieXqGhJZocJHMZGGhrJWw+h+FrbzAEEfB2sW/jFzIMVCgJJaoey6TUGQe3VBaI8TSgakg40i9nLhI/3wkbg0dLvPd+01pI8zNAaY4LbgxhuyNAsYbrh+WM0oIlZmIbMG0hHMVXQKd+l6lm/6U63dIwHENEK1iZdU4xrzruGCshGivqHo+AR8zZjrc7d3aBS2ixDrv3yLMUgqg=
      run: 
  - stage: deploy frontend to production
    language: node_js
    node_js:
    - stable
    cache:
      directories:
      - client/node_modules
    script:
    - cd frontend
    deploy:
      provider: heroku
      app: yefdebugfrontend
      api_key:
        secure: c8QnQxTURPFWzXqNdzsrrVH7ebDy8tPEEztES4Cpc19Ol4KpKTVIc4JTO0v+RzFGVmHRE83N0E8gVtmLVKxQvPo6cXZqPGUM+zl7j7FHSSwUqIghTIWilHTakUb9LkP3kA6eMCSOQDx9N0MYlCnSumGpambb/lMY63M/iOHNiHaXcgkF3BHs2HSAbZSxNrRL00V9ZJKfThGfeZsDZeePAPeiADqzrNsMnQ9buMTgbNKemYy95eircop6CvIJF5ANFCQeth2YxM47Lq5i6MoGy1KVxDb0KMiB72gzXK+bnsNOv/h3oXY9sLcOmOUPiQ6xv6gip1ijSmXLV4lFIRhvUu2dwXRxxVYczFbRz4MNjmKiC9xt0rEOt6wZu1D2nm6S8h8YbhrZZf8pBpAi3hNIiHhauYXwvZZ70UtzIUinjook6BSz+thbS3BG+KaaLMjC51oagfP57oN4x+n9UvlWmNszY+hXg4GIliPdlHwddBWdKnoK9xBIj0JARQ46rEOBYHGsTHHJB/SESmqqwyBLx5J0Vwt2Lu8zZECgDId1ZWAEL7a5INszdyBkhlQdKt/uJr/e94Ld4oXdBXY8svL7FE/5FqsClDGJ1tjZ0uaLnnP1E94PuxfNZ0Ye6wrfv+mcj2FJ8Cby5vfr8g5zBMSls4/OfJIS2NtzDEZLlyRZPgE=
