notifications:
  email: false
jobs:
  include:
  - stage: deploy backend to production
    language: python
    python:
    - '3.6'
    services:
    - postgresql
    addons:
      postgresql: '9.6'
    before_install:
    - cd backend
    install:
    - pip install -r requirements.txt
    before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    script: python manage.py test api
    deploy:
      provider: heroku
      app: yefdebug
      api_key:
        secure: S3NqZe8iTFK1MJo+csnlzbBFntvRUccN3+pJaNmdTvzyFnaoAW/T00BZcX40flWHPWfI0XOpoM7+IjqcHnEq/7Ad4DhekJE+VSbGrAqVRtFOLpLyVYfHwgs+G2/9dBw9S2H2u4G8zL20bPZIlRGyXnpW2g5iBfRli6I1p0gbrUBWP/Jqfs4kYfz+3Tqiy7pyWG4+Mo48MoH4UQ5PMpxH8IfxTGnGd5fKwIJ2cZ7uczsXvVWD5zk/EmpQRW/21ndRkRQGt5IcAJXCS7UCC9HfTOUUz6l/zz4ZkudS/4fsWG9pgT1NFMeYJQFSlylPMf/y0GhIUSIMn0XF3GiHFbonbXhm6tZ+5t7iAma9WXJarrpJ1DgGAdenvE/t6CdAGKnPVEO1xzNPhjlpUmwoaU1j1xBWMu8nMD9QK9CKSX8nTN17Ijjr0TyP3X6kRhS6WcJQrC/MlQ3re2Q7IgQ4id1YZt87UOjwutvWQKR5sZkJNVTvZCL6shdqSWcWIfObcFnxpZQP2v+6J48AJagxr9MEK89h3VguOWh4+0/RLpbsrAdp7YW28//FboFKfF0m2ZIYhnuF6v53cYVKltTCo29bxh9ZAJvhN5u7Wzs2ZiIae2DuB9uz4mpkXvl7bcmGF3xygVFZ3Wr0yhgruHg+LUvvUihijKqPeL8u59NQQSkNu+U=
  - stage: deploy frontend to production
    language: node_js
    node_js:
    - stable
    cache:
      directories:
      - client/node_modules
    before_install:
    - cd frontend
    install:
    - yarn
    script: echo foo
    deploy:
      provider: heroku
      app: yefdebugfrontend
      api_key:
        secure: S3NqZe8iTFK1MJo+csnlzbBFntvRUccN3+pJaNmdTvzyFnaoAW/T00BZcX40flWHPWfI0XOpoM7+IjqcHnEq/7Ad4DhekJE+VSbGrAqVRtFOLpLyVYfHwgs+G2/9dBw9S2H2u4G8zL20bPZIlRGyXnpW2g5iBfRli6I1p0gbrUBWP/Jqfs4kYfz+3Tqiy7pyWG4+Mo48MoH4UQ5PMpxH8IfxTGnGd5fKwIJ2cZ7uczsXvVWD5zk/EmpQRW/21ndRkRQGt5IcAJXCS7UCC9HfTOUUz6l/zz4ZkudS/4fsWG9pgT1NFMeYJQFSlylPMf/y0GhIUSIMn0XF3GiHFbonbXhm6tZ+5t7iAma9WXJarrpJ1DgGAdenvE/t6CdAGKnPVEO1xzNPhjlpUmwoaU1j1xBWMu8nMD9QK9CKSX8nTN17Ijjr0TyP3X6kRhS6WcJQrC/MlQ3re2Q7IgQ4id1YZt87UOjwutvWQKR5sZkJNVTvZCL6shdqSWcWIfObcFnxpZQP2v+6J48AJagxr9MEK89h3VguOWh4+0/RLpbsrAdp7YW28//FboFKfF0m2ZIYhnuF6v53cYVKltTCo29bxh9ZAJvhN5u7Wzs2ZiIae2DuB9uz4mpkXvl7bcmGF3xygVFZ3Wr0yhgruHg+LUvvUihijKqPeL8u59NQQSkNu+U=